### PR TITLE
send local files using cntb for your bucket

### PR DESCRIPTION
**Pull request by jos3duardo**
This PR is to help other users like me to upload local files or files on their servers to the bucket in contabo storage. I had to search a lot and I almost gave up on using this, but I finally managed to get it right after hitting the correct region, because in the official documentation there is no such region pattern in the examples

### CODE REVIEW

**Comment by ikhan009** [comment]
please guide me, how i run cntb on liunx? i uploaded linux zip file on server, and make it unzip, but cntb not working, give error.
cntb help
-bash: cntb: command not found

how i run it on liux, i don't know, in documentation they don't mention.

**Review by tahergalal — COMMENTED** [review]
You can find the region of your bucket by calling the bellow command is better english

**Comment by jos3duardo** [comment]
> You can find the region of your bucket by calling the bellow command is better english

tanks for your observations!

**Comment by jos3duardo** [comment]
> Changes from this PR disappeared from README, why?

i dont know, but is a good question

**Pull request merged**
